//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hspi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hspi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///Chosen, a Select Box Enhancer for jQuery and Prototype
        ///by Patrick Filler for Harvest, http://getharvest.com
        ///
        ///Version 1.8.5
        ///Full source at https://github.com/harvesthq/chosen
        ///Copyright (c) 2011-2018 Harvest http://getharvest.com
        ///
        ///MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
        ///This file is generated by `grunt build`, do not edit it by hand.
        ///*/
        ///
        ////* @group Base */
        ///.chosen-container {
        ///  position: relative;
        ///  display: inline-block;
        ///  vertical-align: middle;
        ///  font-size: 13px;
        ///  -webki [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chosen_css {
            get {
                return ResourceManager.GetString("chosen_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Chosen v1.8.5 | (c) 2011-2018 by Harvest | MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md */
        ///
        ///(function(){var t,e,s,i,n=function(t,e){return function(){return t.apply(e,arguments)}},o=function(t,e){function s(){this.constructor=t}for(var i in e)r.call(e,i)&amp;&amp;(t[i]=e[i]);return s.prototype=e.prototype,t.prototype=new s,t.__super__=e.prototype,t},r={}.hasOwnProperty;(i=function(){function t(){this.options_index=0,this.parsed=[]}return t.prototype.add_node=function(t){return&quot;OPTGROUP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chosen_jquery_min_js {
            get {
                return ResourceManager.GetString("chosen_jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Table styles
        /// */
        ///table.dataTable {
        ///  width: 100%;
        ///  margin: 0 auto;
        ///  clear: both;
        ///  border-collapse: separate;
        ///  border-spacing: 0;
        ///  /*
        ///   * Header and footer styles
        ///   */
        ///  /*
        ///   * Body styles
        ///   */ }
        ///  table.dataTable thead th,
        ///  table.dataTable tfoot th {
        ///    font-weight: bold; }
        ///  table.dataTable thead th,
        ///  table.dataTable thead td {
        ///    padding: 10px 18px;
        ///    border-bottom: 1px solid #111111; }
        ///    table.dataTable thead th:active,
        ///    table.dataTable thead td:active {
        ///      outline: none; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_dataTables_css {
            get {
                return ResourceManager.GetString("jquery_dataTables_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// DataTables 1.10.16
        /// ©2008-2017 SpryMedia Ltd - datatables.net/license
        ///*/
        ///(function(h){&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],function(E){return h(E,window,document)}):&quot;object&quot;===typeof exports?module.exports=function(E,G){E||(E=window);G||(G=&quot;undefined&quot;!==typeof window?require(&quot;jquery&quot;):require(&quot;jquery&quot;)(E));return h(G,E,E.document)}:h(jQuery,window,document)})(function(h,E,G,k){function X(a){var b,c,d={};h.each(a,function(e){if((b=e.match(/^([^A-Z]+?)([A-Z])/))&amp;&amp;-1!==&quot;a aa ai ao as b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_dataTables_min_js {
            get {
                return ResourceManager.GetString("jquery_dataTables_min_js", resourceCulture);
            }
        }
    }
}
