//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hspi {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hspi.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///Chosen, a Select Box Enhancer for jQuery and Prototype
        ///by Patrick Filler for Harvest, http://getharvest.com
        ///
        ///Version 1.8.5
        ///Full source at https://github.com/harvesthq/chosen
        ///Copyright (c) 2011-2018 Harvest http://getharvest.com
        ///
        ///MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md
        ///This file is generated by `grunt build`, do not edit it by hand.
        ///*/
        ///
        ////* @group Base */
        ///.chosen-container {
        ///  position: relative;
        ///  display: inline-block;
        ///  vertical-align: middle;
        ///  font-size: 13px;
        ///  -webki [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chosen_css {
            get {
                return ResourceManager.GetString("chosen_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Chosen v1.8.5 | (c) 2011-2018 by Harvest | MIT License, https://github.com/harvesthq/chosen/blob/master/LICENSE.md */
        ///
        ///(function(){var t,e,s,i,n=function(t,e){return function(){return t.apply(e,arguments)}},o=function(t,e){function s(){this.constructor=t}for(var i in e)r.call(e,i)&amp;&amp;(t[i]=e[i]);return s.prototype=e.prototype,t.prototype=new s,t.__super__=e.prototype,t},r={}.hasOwnProperty;(i=function(){function t(){this.options_index=0,this.parsed=[]}return t.prototype.add_node=function(t){return&quot;OPTGROUP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string chosen_jquery_min_js {
            get {
                return ResourceManager.GetString("chosen_jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // https://d3js.org Version 5.4.0. Copyright 2018 Mike Bostock.
        ///(function(t,n){&quot;object&quot;==typeof exports&amp;&amp;&quot;undefined&quot;!=typeof module?n(exports):&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;exports&quot;],n):n(t.d3=t.d3||{})})(this,function(t){&quot;use strict&quot;;function n(t,n){return t&lt;n?-1:t&gt;n?1:t&gt;=n?0:NaN}function e(t){return 1===t.length&amp;&amp;(t=function(t){return function(e,r){return n(t(e),r)}}(t)),{left:function(n,e,r,i){for(null==r&amp;&amp;(r=0),null==i&amp;&amp;(i=n.length);r&lt;i;){var o=r+i&gt;&gt;&gt;1;t(n[o],e)&lt;0?r=o+1:i=o}return r},ri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string d3_min_js {
            get {
                return ResourceManager.GetString("d3_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! iFrame Resizer (iframeSizer.contentWindow.min.js) - v3.6.1 - 2018-04-29
        /// *  Desc: Include this file in any page being loaded into an iframe
        /// *        to force the iframe to resize to the content size.
        /// *  Requires: iframeResizer.min.js on host page.
        /// *  Copyright: (c) 2018 David J. Bradshaw - dave@bradshaw.net
        /// *  License: MIT
        /// */
        ///
        ///!function(a){&quot;use strict&quot;;function b(a,b,c){&quot;addEventListener&quot;in window?a.addEventListener(b,c,!1):&quot;attachEvent&quot;in window&amp;&amp;a.attachEvent(&quot;on&quot;+b,c)}function c(a,b,c){&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iframeResizer_contentWindow_min_js {
            get {
                return ResourceManager.GetString("iframeResizer_contentWindow_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! iFrame Resizer (iframeSizer.min.js ) - v3.6.1 - 2018-04-29
        /// *  Desc: Force cross domain iframes to size to content.
        /// *  Requires: iframeResizer.contentWindow.min.js to be loaded into the target frame.
        /// *  Copyright: (c) 2018 David J. Bradshaw - dave@bradshaw.net
        /// *  License: MIT
        /// */
        ///
        ///!function(a){&quot;use strict&quot;;function b(a,b,c){&quot;addEventListener&quot;in window?a.addEventListener(b,c,!1):&quot;attachEvent&quot;in window&amp;&amp;a.attachEvent(&quot;on&quot;+b,c)}function c(a,b,c){&quot;removeEventListener&quot;in window?a.removeEventListene [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string iframeSizer_min_js {
            get {
                return ResourceManager.GetString("iframeSizer_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        /// * Table styles
        /// */
        ///table.dataTable {
        ///  width: 100%;
        ///  margin: 0 auto;
        ///  clear: both;
        ///  border-collapse: separate;
        ///  border-spacing: 0;
        ///  /*
        ///   * Header and footer styles
        ///   */
        ///  /*
        ///   * Body styles
        ///   */ }
        ///  table.dataTable thead th,
        ///  table.dataTable tfoot th {
        ///    font-weight: bold; }
        ///  table.dataTable thead th,
        ///  table.dataTable thead td {
        ///    padding: 10px 18px;
        ///    border-bottom: 1px solid #111111; }
        ///    table.dataTable thead th:active,
        ///    table.dataTable thead td:active {
        ///      outline: none; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_dataTables_css {
            get {
                return ResourceManager.GetString("jquery_dataTables_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// DataTables 1.10.16
        /// ©2008-2017 SpryMedia Ltd - datatables.net/license
        ///*/
        ///(function(h){&quot;function&quot;===typeof define&amp;&amp;define.amd?define([&quot;jquery&quot;],function(E){return h(E,window,document)}):&quot;object&quot;===typeof exports?module.exports=function(E,G){E||(E=window);G||(G=&quot;undefined&quot;!==typeof window?require(&quot;jquery&quot;):require(&quot;jquery&quot;)(E));return h(G,E,E.document)}:h(jQuery,window,document)})(function(h,E,G,k){function X(a){var b,c,d={};h.each(a,function(e){if((b=e.match(/^([^A-Z]+?)([A-Z])/))&amp;&amp;-1!==&quot;a aa ai ao as b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_dataTables_min_js {
            get {
                return ResourceManager.GetString("jquery_dataTables_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .mg-active-datapoint {
        ///    fill: black;
        ///    font-size: 0.9rem;
        ///    font-weight: 400;
        ///    opacity: 0.8;
        ///}
        ///
        ///.mg-area1-color {
        ///    fill: #0000ff;
        ///}
        ///
        ///.mg-area2-color {
        ///    fill: #05b378;
        ///}
        ///
        ///.mg-area3-color {
        ///    fill: #db4437;
        ///}
        ///
        ///.mg-area4-color {
        ///    fill: #f8b128;
        ///}
        ///
        ///.mg-area5-color {
        ///    fill: #5c5c5c;
        ///}
        ///
        ///text.mg-barplot-group-label {
        ///    font-weight:900;
        ///}
        ///
        ///.mg-barplot rect.mg-bar {
        ///    shape-rendering: auto;
        ///}
        ///
        ///.mg-barplot rect.mg-bar.default-bar {
        ///    fill: #b6b6fc;
        ///}
        ///
        ///.mg-barplot rect.mg-bar.default-acti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metricsgraphics_css {
            get {
                return ResourceManager.GetString("metricsgraphics_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !function(t,e){&quot;function&quot;==typeof define&amp;&amp;define.amd?define([&quot;d3&quot;],e):&quot;object&quot;==typeof exports?module.exports=e(require(&quot;d3&quot;)):t.MG=e(t.d3)}(this,function(t){function e(){return&quot;undefined&quot;!=typeof jQuery||&quot;undefined&quot;!=typeof $}function r(t){var e;switch(t.processed.x_time_frame){case&quot;millis&quot;:e=MG.time_format(t.utc_time,&quot;%b %e, %Y  %H:%M:%S.%L&quot;);break;case&quot;seconds&quot;:e=MG.time_format(t.utc_time,&quot;%b %e, %Y  %H:%M:%S&quot;);break;case&quot;less-than-a-day&quot;:e=MG.time_format(t.utc_time,&quot;%b %e, %Y  %I:%M%p&quot;);break;case&quot;four- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string metricsgraphics_min_js {
            get {
                return ResourceManager.GetString("metricsgraphics_min_js", resourceCulture);
            }
        }
    }
}
